// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/media/v1/media.proto

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadRequest contains file data for upload
type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                                                           // Original file name
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                                                             // File content
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                                                  // MIME type (e.g., "image/jpeg")
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UploadStreamRequest for streaming file uploads
type UploadStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadStreamRequest_Metadata
	//	*UploadStreamRequest_Chunk
	Data          isUploadStreamRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStreamRequest) Reset() {
	*x = UploadStreamRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStreamRequest) ProtoMessage() {}

func (x *UploadStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStreamRequest.ProtoReflect.Descriptor instead.
func (*UploadStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadStreamRequest) GetData() isUploadStreamRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadStreamRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadStreamRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadStreamRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadStreamRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadStreamRequest_Data interface {
	isUploadStreamRequest_Data()
}

type UploadStreamRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // First message contains metadata
}

type UploadStreamRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // Subsequent messages contain chunks
}

func (*UploadStreamRequest_Metadata) isUploadStreamRequest_Data() {}

func (*UploadStreamRequest_Chunk) isUploadStreamRequest_Data() {}

// FileMetadata contains file information
type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_media_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *FileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileMetadata) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UploadResponse returns the uploaded file information
type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`       // Storage path/key
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                                 // Public URL
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`      // File size in bytes
	UploadedAt    string                 `protobuf:"bytes,4,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"` // Upload timestamp (RFC3339)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadResponse) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

// DownloadRequest specifies which file to download
type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // Storage path/key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// DownloadResponse returns the file data
type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`          // Original file name
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                            // File content
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`         // File size in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DownloadResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DownloadResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DownloadResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

// DownloadStreamResponse for streaming file downloads
type DownloadStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*DownloadStreamResponse_Metadata
	//	*DownloadStreamResponse_Chunk
	Data          isDownloadStreamResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadStreamResponse) Reset() {
	*x = DownloadStreamResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadStreamResponse) ProtoMessage() {}

func (x *DownloadStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadStreamResponse.ProtoReflect.Descriptor instead.
func (*DownloadStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadStreamResponse) GetData() isDownloadStreamResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadStreamResponse) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*DownloadStreamResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *DownloadStreamResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*DownloadStreamResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isDownloadStreamResponse_Data interface {
	isDownloadStreamResponse_Data()
}

type DownloadStreamResponse_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // First message contains metadata
}

type DownloadStreamResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // Subsequent messages contain chunks
}

func (*DownloadStreamResponse_Metadata) isDownloadStreamResponse_Data() {}

func (*DownloadStreamResponse_Chunk) isDownloadStreamResponse_Data() {}

// DeleteRequest specifies which file to delete
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // Storage path/key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// DeleteResponse confirms deletion
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether deletion was successful
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Optional message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetURLRequest specifies which file URL to retrieve
type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // Storage path/key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetURLRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// GetURLResponse returns the file URL
type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                              // Public URL
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Expiration time if applicable (RFC3339)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{10}
}

func (x *GetURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetURLResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// GetFileInfoRequest specifies which file info to retrieve
type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // Storage path/key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_proto_media_v1_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileInfoRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// GetFileInfoResponse returns file metadata
type GetFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                                                           // Storage path/key
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                                                           // Original file name
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                                                  // MIME type
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                                                          // File size in bytes
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                                                                     // Public URL
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                        // Creation timestamp (RFC3339)
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoResponse) Reset() {
	*x = GetFileInfoResponse{}
	mi := &file_proto_media_v1_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResponse) ProtoMessage() {}

func (x *GetFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_v1_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_v1_media_proto_rawDescGZIP(), []int{12}
}

func (x *GetFileInfoResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetFileInfoResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetFileInfoResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetFileInfoResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GetFileInfoResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetFileInfoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetFileInfoResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_media_v1_media_proto protoreflect.FileDescriptor

const file_proto_media_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/media/v1/media.proto\x12\bmedia.v1\"\xe9\x01\n" +
	"\rUploadRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.media.v1.UploadRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x13UploadStreamRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.media.v1.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\xea\x01\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.media.v1.FileMetadata.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x0eUploadResponse\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1f\n" +
	"\vuploaded_at\x18\x04 \x01(\tR\n" +
	"uploadedAt\".\n" +
	"\x0fDownloadRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"\x89\x01\n" +
	"\x10DownloadResponse\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\"n\n" +
	"\x16DownloadStreamResponse\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.media.v1.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\",\n" +
	"\rDeleteRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\rGetURLRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"A\n" +
	"\x0eGetURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"1\n" +
	"\x12GetFileInfoRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"\xc6\x02\n" +
	"\x13GetFileInfoResponse\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12G\n" +
	"\bmetadata\x18\a \x03(\v2+.media.v1.GetFileInfoResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf0\x03\n" +
	"\fMediaService\x12;\n" +
	"\x06Upload\x12\x17.media.v1.UploadRequest\x1a\x18.media.v1.UploadResponse\x12I\n" +
	"\fUploadStream\x12\x1d.media.v1.UploadStreamRequest\x1a\x18.media.v1.UploadResponse(\x01\x12A\n" +
	"\bDownload\x12\x19.media.v1.DownloadRequest\x1a\x1a.media.v1.DownloadResponse\x12O\n" +
	"\x0eDownloadStream\x12\x19.media.v1.DownloadRequest\x1a .media.v1.DownloadStreamResponse0\x01\x12;\n" +
	"\x06Delete\x12\x17.media.v1.DeleteRequest\x1a\x18.media.v1.DeleteResponse\x12;\n" +
	"\x06GetURL\x12\x17.media.v1.GetURLRequest\x1a\x18.media.v1.GetURLResponse\x12J\n" +
	"\vGetFileInfo\x12\x1c.media.v1.GetFileInfoRequest\x1a\x1d.media.v1.GetFileInfoResponseB;Z9github.com/khdiyz/media-service/genproto/media/v1;mediav1b\x06proto3"

var (
	file_proto_media_v1_media_proto_rawDescOnce sync.Once
	file_proto_media_v1_media_proto_rawDescData []byte
)

func file_proto_media_v1_media_proto_rawDescGZIP() []byte {
	file_proto_media_v1_media_proto_rawDescOnce.Do(func() {
		file_proto_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_v1_media_proto_rawDesc), len(file_proto_media_v1_media_proto_rawDesc)))
	})
	return file_proto_media_v1_media_proto_rawDescData
}

var file_proto_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_media_v1_media_proto_goTypes = []any{
	(*UploadRequest)(nil),          // 0: media.v1.UploadRequest
	(*UploadStreamRequest)(nil),    // 1: media.v1.UploadStreamRequest
	(*FileMetadata)(nil),           // 2: media.v1.FileMetadata
	(*UploadResponse)(nil),         // 3: media.v1.UploadResponse
	(*DownloadRequest)(nil),        // 4: media.v1.DownloadRequest
	(*DownloadResponse)(nil),       // 5: media.v1.DownloadResponse
	(*DownloadStreamResponse)(nil), // 6: media.v1.DownloadStreamResponse
	(*DeleteRequest)(nil),          // 7: media.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 8: media.v1.DeleteResponse
	(*GetURLRequest)(nil),          // 9: media.v1.GetURLRequest
	(*GetURLResponse)(nil),         // 10: media.v1.GetURLResponse
	(*GetFileInfoRequest)(nil),     // 11: media.v1.GetFileInfoRequest
	(*GetFileInfoResponse)(nil),    // 12: media.v1.GetFileInfoResponse
	nil,                            // 13: media.v1.UploadRequest.MetadataEntry
	nil,                            // 14: media.v1.FileMetadata.MetadataEntry
	nil,                            // 15: media.v1.GetFileInfoResponse.MetadataEntry
}
var file_proto_media_v1_media_proto_depIdxs = []int32{
	13, // 0: media.v1.UploadRequest.metadata:type_name -> media.v1.UploadRequest.MetadataEntry
	2,  // 1: media.v1.UploadStreamRequest.metadata:type_name -> media.v1.FileMetadata
	14, // 2: media.v1.FileMetadata.metadata:type_name -> media.v1.FileMetadata.MetadataEntry
	2,  // 3: media.v1.DownloadStreamResponse.metadata:type_name -> media.v1.FileMetadata
	15, // 4: media.v1.GetFileInfoResponse.metadata:type_name -> media.v1.GetFileInfoResponse.MetadataEntry
	0,  // 5: media.v1.MediaService.Upload:input_type -> media.v1.UploadRequest
	1,  // 6: media.v1.MediaService.UploadStream:input_type -> media.v1.UploadStreamRequest
	4,  // 7: media.v1.MediaService.Download:input_type -> media.v1.DownloadRequest
	4,  // 8: media.v1.MediaService.DownloadStream:input_type -> media.v1.DownloadRequest
	7,  // 9: media.v1.MediaService.Delete:input_type -> media.v1.DeleteRequest
	9,  // 10: media.v1.MediaService.GetURL:input_type -> media.v1.GetURLRequest
	11, // 11: media.v1.MediaService.GetFileInfo:input_type -> media.v1.GetFileInfoRequest
	3,  // 12: media.v1.MediaService.Upload:output_type -> media.v1.UploadResponse
	3,  // 13: media.v1.MediaService.UploadStream:output_type -> media.v1.UploadResponse
	5,  // 14: media.v1.MediaService.Download:output_type -> media.v1.DownloadResponse
	6,  // 15: media.v1.MediaService.DownloadStream:output_type -> media.v1.DownloadStreamResponse
	8,  // 16: media.v1.MediaService.Delete:output_type -> media.v1.DeleteResponse
	10, // 17: media.v1.MediaService.GetURL:output_type -> media.v1.GetURLResponse
	12, // 18: media.v1.MediaService.GetFileInfo:output_type -> media.v1.GetFileInfoResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_media_v1_media_proto_init() }
func file_proto_media_v1_media_proto_init() {
	if File_proto_media_v1_media_proto != nil {
		return
	}
	file_proto_media_v1_media_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadStreamRequest_Metadata)(nil),
		(*UploadStreamRequest_Chunk)(nil),
	}
	file_proto_media_v1_media_proto_msgTypes[6].OneofWrappers = []any{
		(*DownloadStreamResponse_Metadata)(nil),
		(*DownloadStreamResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_v1_media_proto_rawDesc), len(file_proto_media_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_v1_media_proto_goTypes,
		DependencyIndexes: file_proto_media_v1_media_proto_depIdxs,
		MessageInfos:      file_proto_media_v1_media_proto_msgTypes,
	}.Build()
	File_proto_media_v1_media_proto = out.File
	file_proto_media_v1_media_proto_goTypes = nil
	file_proto_media_v1_media_proto_depIdxs = nil
}
